create table rental(
RID NUMBER PRIMARY KEY,

MID NUMBER NOT NULL,
CONSTRAINT FK_RENTAL FOREIGN KEY(MID)
REFERENCES MEMBER1 (MID);
ALTER TABLE RENTAL
ADD CONSTRAINT MID FOREIGN KEY(MID)
REFERENCES MEMBER2(MID1);


BID NUMBER NOT NULL,
CONSTRAINT FK_RENTAL FOREIGN KEY(BID)
REFERENCES BOOK (BID),

RENTAL DATE NOT NULL,
ENDRENTAL DATE NOT NULL);

CREATE SEQUENCE SEQMEMBER;
create table BOOK(
BID NUMBER PRIMARY KEY,
ISBN NUMBER(20) NOT NULL ,
TITLE VARCHAR2(10) NOT NULL,
AUTHOR VARCHAR2(10),
PUBLISHER VARCHAR2(10) NOT NULL,
LOCATION_1 VARCHAR2(10) NOT NULL,
BOOKSTATE VARCHAR2(10) NOT NULL);
CREATE SEQUENCE SEQMEMBER;

create table MEMBER1(
MID NUMBER PRIMARY KEY,
MNAME VARCHAR2(10) NOT NULL,
MGRADE VARCHAR2(10) NOT NULL,
MPHONE VARCHAR2(10) NOT NULL,
MAXRENTAL VARCHAR2(10) NOT NULL);

LOCATION1 VARCHAR2(10) NOT NULL,
BOOKSTATE VARCHAR2(10) NOT NULL);


INSERT INTO TBLMEMBER(IDX,NAME,PHONE,TEAM)
VALUES(SEQMEMBER.NEXTVAL, '홍길동','010-5555-6666','산적');
INSERT INTO TBLMEMBER(IDX,NAME,PHONE,TEAM)
VALUES(SEQMEMBER.NEXTVAL, '강호동','010-7878-7878','MC');
INSERT INTO TBLMEMBER(IDX,NAME,PHONE,TEAM)
VALUES(SEQMEMBER.NEXTVAL, '장동건','010-1212-1212','배우');
select * from tblmember;
SELECT * FROM RENTAL;
DROP TABLE MEMBER;