create table tblMember(
idx NUMBER PRIMARY KEY,
NAME VARCHAR2(10) NOT NULL,
PHONE VARCHAR2(13) NOT NULL,
TEAM VARCHAR2(10) NOT NULL);

CREATE SEQUENCE SEQMEMBER;

INSERT INTO TBLMEMBER(IDX,NAME,PHONE,TEAM)
VALUES(SEQMEMBER.NEXTVAL, '홍길동','010-5555-6666','산적');